#spring:
#  datasource:
#    url: jdbc:mysql://us-cdbr-east-02.cleardb.com:3306/heroku_63cfcabab806293?serverTimezone=Turkey
#    username: root
#    password: f99d9575
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/airline?serverTimezone=Turkey
#    username: bdd5d238e023ce
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:#    user:#      password: 123
#  jpa:#    hibernate:#      ddl-auto: create-drop
#    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#server:#  port: 0
#  
#logging:#  level:#    sql: debug
#    org.thymeleaf.spring5: debug
        